spring:
    profiles:
         active:
              - dev


---
server:
  port: 8201
spring:
      profiles: dev
      application:
            name:  cbg-dev
eureka:

  client:
        service-url:
                  defaultZone: http://eureka-dev.com:7001/eureka/




---