spring:
    profiles:
         active:
              - dev


---
server:
  port: 8203
spring:
      profiles: dev
      application:
            name:  cbg-dev
eureka:

  client:
        service-url:
                  defaultZone: http://localhost:7001/eureka/
chen:
    info: chen



---
